---

- hosts: all
  become: true
  tasks:
  - name : Run update on Ubuntu
    when: ansible_facts['os_family'] == "Debian"
    apt:
      update_cache: yes

- hosts: all
  become: true
  tasks:
  - name : Run update on CentOS
    when: ansible_facts['os_family'] == "RedHat"
    vars:
       ansible_python_interpreter: /usr/bin/python3
    dnf:
#     update_cache: yes
      name: "*"
      state: latest

- hosts: jenkinsServer
  become: true
  tasks:
  - name : install vim-nox on Jenkins Server
    vars:
       ansible_python_interpreter: /usr/bin/python3
    yum:
      name: httpd
      state: latest
- hosts: liquibaseServer
  become: true
#  become_user: ubuntu
  tasks:
  - name : install vim-nox on Liquibase Server
    apt:
      name: vim-nox
      state: latest
- hosts: AngularServer
  become: true
#  become_user: javed
#  become_method: sudo
  tasks:
#  - name: Update package list
#    apt:
#      update_cache: yes
  - name : install vim-nox on Angular Server
    apt:
      name: vim-nox
      state: latest

